# Generated by Django 3.0 on 2019-12-12 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(default='', max_length=200)),
                ('url_video', models.CharField(default='', max_length=200)),
                ('author', models.CharField(default='', max_length=200)),
                ('tanggal_upload', models.DateTimeField(verbose_name='Waktu Upload')),
            ],
        ),
    ]
