# Generated by Django 3.0 on 2019-12-12 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youtubeapp', '0002_video_foto_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='tanggal_upload',
            new_name='waktu_upload',
        ),
    ]
