# Generated by Django 3.0 on 2019-12-12 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtubeapp', '0005_urlunik'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='unik',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.DeleteModel(
            name='URLUnik',
        ),
    ]
