# Generated by Django 3.0 on 2019-12-12 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtubeapp', '0006_auto_20191212_1100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='unik',
        ),
        migrations.AddField(
            model_name='video',
            name='embed',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='video',
            name='thumbnail',
            field=models.CharField(default='', max_length=200),
        ),
    ]
