# Generated by Django 3.0 on 2019-12-12 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtubeapp', '0007_auto_20191212_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='jumlah_view',
            field=models.IntegerField(default=0),
        ),
    ]
